export const TELUGU_MOVIES = [
  'Bahubali',
  'Bahubali 2',
  'RRR',
  'Pushpa',
  'Pushpa 2',
  'Ala Vaikunthapurramuloo',
  'Arjun Reddy',
  'Jersey',
  'Maharshi',
  'Sarileru Neekevvaru',
  'Attarintiki Daredi',
  'Magadheera',
  'Eega',
  'Rangasthalam',
  'Uppena',
  'Khaidi No 150',
  'Sye Raa Narasimha Reddy',
  'Bheemla Nayak',
  'Gabbar Singh',
  'Pokiri',
  'Bommarillu',
  'Arya',
  'Arya 2',
  'Leader',
  'Sankarabharanam',
  'Geetha Govindam',
  'Mr Perfect',
  'Darling',
  'Temper',
  'Janatha Garage',
  'Nannu Dochukunduvate',
  'Hello',
  'Fidaa',
  'Love Story',
  'Vakeel Saab',
  'Goodachari',
  'Gaami',
  'Hi Nanna',
  'Bhagavanth Kesari',
  'Dasara',
  'Hanu Man',
  'Karthikeya 2',
  'Majili',
  'Sammohanam',
  'Sita Ramam',
  'Mathu Vadalara',
  'F2',
  'F3',
  'Supreme',
  'Dhruva',
  'Jai Lava Kusa',
  'Acharya',
  'Chirutha',
  'Mirchi',
  'Saaho',
  'Salaar',
  'Kalki 2898 AD',
  'Khaleja',
  'Dookudu',
  'Okkadu',
  'Murari',
  'Pelli Choopulu',
  'Yevade Subramanyam',
  'Mahanati',
  'Shyam Singha Roy',
  'Virupaksha',
  'HIT',
  'HIT 2',
  'God Father',
  'Agent Sai Srinivasa Athreya',
  'Balagam',
  'Seethamma Vakitlo Sirimalle Chettu',
  'Race Gurram',
  'Taxi Waala',
  'Savyasachi',
  'iSmart Shankar',
  'DJ Tillu',
  'Tillu Square',
  'Jathi Ratnalu',
  'Swathi Muthyam',
  'Mayabazar'
];
